---
# handlers file for nullmailer
- name:        restart_nullmailer
  service:     
    name:      nullmailer
    state:     restarted
    enabled:   yes
  become:      True
  become_user: '{{ nullmailer_become_user }}'
